[font]
normal = { family = "JetBrainsMono"}

size = 12

[shell]
program = "/bin/zsh"




[colors.primary]
    background = '#32302f'
    foreground = '#d4be98'

[colors.normal]
    black =   '#45403d'
    red =     '#ea6962'
    green =   '#a9b665'
    yellow =  '#d8a657'
    blue =    '#7daea3'
    magenta = '#d3869b'
    cyan =    '#89b482'
    white =   '#d4be98'

[colors.bright]
      black =   '#45403d'
      red =     '#ea6962'
      green =   '#a9b665'
      yellow =  '#d8a657'
      blue =    '#7daea3'
      magenta = '#d3869b'
      cyan =    '#89b482'
      white =   '#d4be98'

